#!/usr/bin/env python
from signal import signal, SIGINT
from thou.crawler import Crawler

def sighandlr(*args):
    c.stop()

if __name__ == '__main__':
    c = Crawler(['https://ycombinator.com', 'https://stackoverflow.com/questions', 'https://en.wikipedia.org'])
    signal(SIGINT, sighandlr)
    c.run_threads(3)
