#!/usr/bin/env python
from signal import signal, SIGINT
from thou.crawler import Crawler

def sighandlr(*args):
    c.stop()

if __name__ == '__main__':
    c = Crawler('https://reddit.com')
    signal(SIGINT, sighandlr)
    c.run_threads(5)
